/* Setting up tables */

CREATE TABLE ARTIST(
	ArtistID		CHAR(200)	PRIMARY KEY,
	FirstName		CHAR(200),
	LastName		CHAR(200),
	DateOfBirth		DATE,
	Facebook		CHAR(200),
	Instagram		CHAR(200),
	Twitter			CHAR(200),
	ProdFlag		BOOLEAN,
	WritFlag		BOOLEAN,
	MusFlag			BOOLEAN,
	VocFlag			BOOLEAN,
	ChorFlag		BOOLEAN,
	TopRange		CHAR(10),
	BottomRange		CHAR(10),
	VoiceType		CHAR(100)
);



CREATE TABLE STAGE_NAME(
	ArtistID	CHAR(200)	PRIMARY KEY,
	StageName	CHAR(200)
);

CREATE TABLE MUSICIAN_INSTRUMENT(
	ID 			int			NOT NULL AUTO_INCREMENT PRIMARY KEY,
	MusicianID	CHAR(200),	
	Instrument	CHAR(200)
);

CREATE TABLE ART_ASSOC_ACTS(
	ID 			int			NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ArtistID	CHAR(200),
	AssocActs	CHAR(200)
);

CREATE TABLE ARTIST_GENRE(
	ID 			int			NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ArtistID	CHAR(200),
	Genre		CHAR(200)
);

CREATE TABLE BAND_MEMBERS(
	ID 			int			NOT NULL AUTO_INCREMENT PRIMARY KEY,
	BandID		CHAR(200),
	ArtistID	CHAR(200)
);


CREATE TABLE BAND(
	BandID		CHAR(200)	PRIMARY KEY,
	BandName	CHAR(200),
	YearCreated	YEAR
);

CREATE TABLE WRITERS_SONGS(
	ID 			int			NOT NULL AUTO_INCREMENT PRIMARY KEY,
	WriterID	CHAR(200),
	SongID		CHAR(200)	
);

CREATE TABLE SONG(
	SongID	CHAR(200)	PRIMARY KEY,
	Title	CHAR(200),
	Length	TIMESTAMP
);

CREATE TABLE SONG_LANG(
	ID 			int			NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SongID		CHAR(200),
	Language	CHAR(200)
);

CREATE TABLE VIDEO(
	VideoID		CHAR(200)	PRIMARY KEY,
	Title 		CHAR(200),
	Length		TIMESTAMP,
	ChoreoName	CHAR(200)
);

CREATE TABLE VIDEO_FOR_SONG(
	SongID	CHAR(200)	PRIMARY KEY,
	VideoID	CHAR(200)
);

CREATE TABLE PLATFORM(
	VideoURL		CHAR(250)	PRIMARY KEY,
	PlatformName	CHAR(200),
	UploadDate		DATE
);

CREATE TABLE VIDEO_LINKS(
	VideoID		CHAR(200)	PRIMARY KEY,
	VideoURL	CHAR(250)	
);

CREATE TABLE ALBUM(
	AlbumID	CHAR(200)	PRIMARY KEY,
	Title	CHAR(200),
	Length TIMESTAMP,
	Date	DATE,
	Label	CHAR(200)
);


CREATE TABLE SONG_INSTRUMENT(
	ID 			int			NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SongID        CHAR(200),
    Instrument    CHAR(200)
);

CREATE TABLE SONG_GENRE(
 	ID 			int			NOT NULL AUTO_INCREMENT PRIMARY KEY,   
	SongID		CHAR(200),
	Genre		CHAR(200)
);

CREATE TABLE PERFORMS(
 	ID 			int			NOT NULL AUTO_INCREMENT PRIMARY KEY,   
	ArtistID	CHAR(200),
	SongID		CHAR(200)
);

CREATE TABLE PRODUCES(
 	ID 			int			NOT NULL AUTO_INCREMENT PRIMARY KEY,   
	ProducerID	CHAR(200),
	SongID		CHAR(200)
);

CREATE TABLE ARTIST_ID_VIDEO_ID(
 	ID 			int			NOT NULL AUTO_INCREMENT PRIMARY KEY,   
	ArtistID	CHAR(200),
	VideoID		CHAR(200)
);

CREATE TABLE DANCE_STYLE(
 	ID 			int			NOT NULL AUTO_INCREMENT PRIMARY KEY,   
	DanceID		CHAR(200),
	Style		CHAR(200)
);

CREATE TABLE CHOREOGRAPHS (
 	ID 				int			NOT NULL AUTO_INCREMENT PRIMARY KEY,   
	ChoreoArtistID	CHAR(200),
	ChoreoName		CHAR(200)
);

CREATE TABLE COMPRISES(
 	ID 				int			NOT NULL AUTO_INCREMENT PRIMARY KEY,   	
	SongID		CHAR(200),
	AlbumID		CHAR(200)
);

CREATE TABLE GOES_ON(
 	ID 			int			NOT NULL AUTO_INCREMENT PRIMARY KEY,   
	ArtistID	CHAR(200),
	TourID		CHAR(200)
);

CREATE TABLE TOUR_DATE(
 	ID 			int			NOT NULL AUTO_INCREMENT PRIMARY KEY,  
	TourID		CHAR(200),
	Date		DATE
);

CREATE TABLE PART_OF_LINEUP(
 	ID 			int			NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	SongID		CHAR(200),
	TourID		CHAR(200)
);

CREATE TABLE ART_AWARDS(
 	ID 			int			NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	ArtistID	CHAR(200),
	Year		YEAR,	
	Award		CHAR(200)
);

CREATE TABLE AWARDS(
	AwardID		CHAR(200)	PRIMARY KEY,
	Institution	CHAR(200),	
	Award		CHAR(200)
);
