/* Setting up tables */

CREATE TABLE ARTIST(
	ArtistID		CHAR(200)	PRIMARY KEY,
	FirstName		CHAR(200),
	LastName		CHAR(200),
	DateOfBirth		DATE,
	Facebook		CHAR(200),
	Instagram		CHAR(200),
	Twitter			CHAR(200),
	ProdFlag		BOOLEAN,
	WritFlag		BOOLEAN,
	MusFlag			BOOLEAN,
	VocFlag			BOOLEAN,
	ChorFlag		BOOLEAN,
	TopRange		CHAR(10),
	BottomRange		CHAR(10),
	VoiceType		CHAR(100)
);

CREATE TABLE STAGE_NAME(
	ArtistID	CHAR(200)	PRIMARY KEY,
	StageName	CHAR(200)
);

/* things not created yet */

CREATE TABLE MUSICIAN_INSTRUMENT(
	MusicianID	CHAR(200)	PRIMARY KEY,
	Instrument	CHAR(200)
);

CREATE TABLE ART_ASSOC_ACTS(
	ArtistID	CHAR(200)	PRIMARY KEY,
	AssocActs	CHAR(200)
);

CREATE TABLE ARTIST_GENRE(
	ArtistID	CHAR(200)	PRIMARY KEY,
	Genre		CHAR(200)
);

CREATE TABLE BAND_MEMBERS(
	BandID		CHAR(200)	PRIMARY KEY,
	ArtistID	CHAR(200)
);

CREATE TABLE BAND(
	BandID		CHAR(200)	PRIMARY KEY,
	BandName	CHAR(200),
	YearCreated	YEAR
);

CREATE TABLE WRITERS_SONGS(
	WriterID	CHAR(200)	PRIMARY KEY,
	SongID		CHAR(200)	
);

CREATE TABLE SONG(
	SongID	CHAR(200)	PRIMARY KEY,
	Title	CHAR(200),
	Length	TIMESTAMP
);

CREATE TABLE SONG_LANG(
	SongID		CHAR(200) PRIMARY KEY,
	Language	CHAR(200)
);

CREATE TABLE VIDEO(
	VideoID		CHAR(200)	PRIMARY KEY,
	Title 		CHAR(200),
	Length		TIMESTAMP,
	ChoreoName	CHAR(200)
);

CREATE TABLE VIDEO_FOR_SONG(
	SongID	CHAR(200)	PRIMARY KEY,
	VideoID	CHAR(200)
);

CREATE TABLE PLATFORM(
	VideoURL		CHAR(250)	PRIMARY KEY,
	PlatformName	CHAR(200),
	UploadDate		DATE
);

CREATE TABLE VIDEO_LINKS(
	VideoID		CHAR(200)	PRIMARY KEY,
	VideoURL	CHAR(250)	
);

CREATE TABLE ALBUM(
	AlbumID	CHAR(200)	PRIMARY KEY,
	Title	CHAR(200),
	Length TIMESTAMP,
	Date	DATE,
	Label	CHAR(200)
);
CREATE TABLE ARTIST(
	ArtistID		CHAR(200)	PRIMARY KEY,
	FirstName		CHAR(200),
	LastName		CHAR(200),
	DateOfBirth		DATE,
	Facebook		CHAR(200),
	Instagram		CHAR(200),
	Twitter			CHAR(200),
	ProdFlag		BOOLEAN,
	WritFlag		BOOLEAN,
	MusFlag			BOOLEAN,
	VocFlag			BOOLEAN,
	ChorFlag		BOOLEAN,
	TopRange		CHAR(10),
	BottomRange		CHAR(10),
	VoiceType		CHAR(100)
);

CREATE TABLE STAGE_NAME(
	ArtistID	CHAR(200)	PRIMARY KEY,
	StageName	CHAR(200)
);

/* things not created yet */

CREATE TABLE MUSICIAN_INSTRUMENT(
	MusicianID	CHAR(200)	PRIMARY KEY,
	Instrument	CHAR(200)
);

CREATE TABLE ART_ASSOC_ACTS(
	ArtistID	CHAR(200)	PRIMARY KEY,
	AssocActs	CHAR(200)
);

CREATE TABLE ARTIST_GENRE(
	ArtistID	CHAR(200)	PRIMARY KEY,
	Genre		CHAR(200)
);

CREATE TABLE BAND_MEMBERS(
	BandID		CHAR(200)	PRIMARY KEY,
	ArtistID	CHAR(200)
);

CREATE TABLE BAND(
	BandID		CHAR(200)	PRIMARY KEY,
	BandName	CHAR(200),
	YearCreated	YEAR
);

CREATE TABLE SONG_INSTRUMENT(
	SongID		CHAR(200)	PRIMARY KEY,
	Instrument	CHAR(200)
);

CREATE TABLE SONG_GENRE(
	SongID		CHAR(200)	PRIMARY KEY,
	Genre		CHAR(200)
);

CREATE TABLE PERFORMS(
	ArtistID	CHAR(200)	PRIMARY KEY,
	SongID		CHAR(200)
);

CREATE TABLE ARTIST_ID_VIDEO_ID(
	ArtistID	CHAR(200)	PRIMARY KEY,
	VideoID		CHAR(200)
);

CREATE TABLE DANCE_STYLE(
	DanceID		CHAR(200)	PRIMARY KEY,
	Style		CHAR(200)
);

CREATE TABLE CHOREOGRAPHS (
	ChoreoArtistID	CHAR(200)	PRIMARY KEY,
	ChoreoName	CHAR(200)
);

CREATE TABLE COMPRISES(
	SongID		CHAR(200)	PRIMARY KEY,
	AlbumID		CHAR(200)
);

CREATE TABLE GOES_ON(
	ArtistID	CHAR(200)	PRIMARY KEY,
	TourID		CHAR(200)
);

CREATE TABLE TOUR_DATE(
	TourID		CHAR(200)	PRIMARY KEY,
	Date		DATE
);

CREATE TABLE PART_OF_LINEUP(
	SongID		CHAR(200)	PRIMARY KEY,
	TourID		CHAR(200)
);

CREATE TABLE ART_AWARDS(
	ArtistID	CHAR(200)	PRIMARY KEY,
	Year		INT	
	Award		CHAR(200)
);

CREATE TABLE AWARDS(
	AwardID		CHAR(200)	PRIMARY KEY,
	Insitution	CHAR(200)	
	Award		CHAR(200)
);
